version: "2"
services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: docker-jenkins
    user: root
    ports:
      - 8180:8080
    volumes:
      - ~/apps/jenkins:/var/jenkins_home
