version: "2"
services:
  es01:
    extends:
      file: ./docker-elasticsearch.yml
      service: es01
  kibana:
    image: kibana:7.9.3
    container_name: docker-kibana
    environment:
      - SERVER_NAME=localhost
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - 5601:5601
    depends_on:
      - es01
