version: "2"
services:
  es01:
    container_name: docker-elastic
    image: elasticsearch:7.9.3
    environment:
      - node.name=es01
      - cluster.name=es_cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - indices.breaker.total.use_real_memory=false
      # - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
