version: "2"
services:
  teamcity-agent:
    image: jetbrains/teamcity-agent:2020.2.1-linux-sudo
    container_name: docker-teamcity-agent
    user: root
    environment:
      - SERVER_URL=http://teamcity-server:8111
      #- DOCKER_IN_DOCKER=start
    volumes:
      #- /var/lib/docker:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/apps/teamcity_agent/conf:/data/teamcity_agent/conf
      - ~/apps/teamcity_agent/work:/opt/buildagent/work
      - ~/apps/teamcity_agent/temp:/opt/buildagent/temp
      - ~/apps/teamcity_agent/tools:/opt/buildagent/tools
      - ~/apps/teamcity_agent/plugins:/opt/buildagent/plugins
      - ~/apps/teamcity_agent/system:/opt/buildagent/system
