version: "2"
services:
  mysql:
    container_name: docker-mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/db-init.sql
    volumes:
        - ./db-init.sql:/data/application/db-init.sql
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234
    ports:
      - 3306:3306
